CREATE TABLE IF NOT EXISTS dwd_enterprise
(
    `eid`         STRING COMMENT '企业id' ,
    `id`     STRING COMMENT '自增序号（非主键）' ,
    `reg_no` STRING COMMENT '注册号' ,
    `credit_no` STRING COMMENT '社会信用代码' ,
    `org_no`       STRING COMMENT '组织机构代码' ,
    `name`     STRING COMMENT '公司名称',
    `format_name`     STRING COMMENT '标准名称',
    `econ_kind`     STRING COMMENT '企业类型',
    `regist_capi`     STRING COMMENT '注册资本',
    `actual_capi`     STRING COMMENT '实收资金',
    `scope`     STRING COMMENT '经营范围',
    `term_start`     STRING COMMENT '经营期限起始日期 YYYY-MM-DD',
    `term_end`     STRING COMMENT '经营期限结束日期 YYYY-MM-DD',
    `check_date`     STRING COMMENT '核准日期 YYYY-MM-DD',
    `belong_org`     STRING COMMENT '登记机关',
    `oper_name`     STRING COMMENT '法定代表人',
    `oper_type`     STRING COMMENT '法定代表人类型',
    `start_date`     STRING COMMENT '成立日期',
    `status`     STRING COMMENT '状态',
    `type_desc`     STRING COMMENT '组织形式',
    `title`     STRING COMMENT '公司代表人职务',
    `longitude`     STRING COMMENT '百度经度',
    `latitude`     STRING COMMENT '百度纬度',
    `gd_longitude`     STRING COMMENT '高德经度',
    `gd_latitude`     STRING COMMENT '高德纬度',
    `collegues_num`     STRING COMMENT '从业人数',
    `created_time`     STRING COMMENT '创建时间',
    `logo_url`     STRING COMMENT '公司logo',
    `url`     STRING COMMENT '工商快照信息url',
    `row_update_time`     STRING COMMENT '变更时间',
    `province_code`     STRING COMMENT '省份代码（新）',
    `district_code`     STRING COMMENT '最优区域码',
    `title_code`     STRING COMMENT '代表人类型代码',
    `econ_kind_code`     STRING COMMENT '企业类型代码',
    `regist_capi_new`     STRING COMMENT '注册资本(新)',
    `currency_unit`     STRING COMMENT '货币单位',
    `revoke_reason`     STRING COMMENT '吊销原因',
    `revoke_date`     STRING COMMENT '吊销日期',
    `logout_reason`     STRING COMMENT '注销原因',
    `logout_date`     STRING COMMENT '注销日期',
    `revoked_certificates`     STRING COMMENT '吊销凭证',
    `new_status_code`     STRING COMMENT '企业状态码',
    `organization_code`     STRING COMMENT '组织分类代码'
)
    COMMENT '企业与立案信息关联表'
    STORED AS ORC;